- hosts: api
  tasks:
#    - name: "Export env variable"
#      lineinfile: 
#        path: /etc/environment
#        line: export DB_HOST=192.168.56.10
    
#    - name: "Export another env"
#      lineinfile:
#        path: /etc/environment
#        line: export DB_USER=root

#    - name: "Export anotherfd env"
#      lineinfile:
#        path: /etc/environment
#        line: export DB_PASS=F&Bb7_T!$RNkgMKn
    
#    - name: "Export anothefr env"
#      lineinfile:
#        path: /etc/environment
#        line: export DB_NAME=movie_db

    - name: "Clone frontend repository"
      git:
        repo   : "{{ movie_analyst_api_repo }}"
        update : yes
        dest   : /home/app

    - name: "Install npm dependencies"
      npm:
        path: /home/app/movie-analyst-api

    - name: "Install MySQL packages"
      apt: pkg={{ item }} state=present
      with_items:
        - mysql-client-core-5.7
        - mysql-client
    
    - name: "Echoing"
      shell: echo $DB_USER - $DB_PASS - $DB_HOST - $DB_PORT

    - name: "Populate DB using mysql-client"
      shell: mysql -u {{ db_user }} -p{{ db_pass }} -h {{ db_host }} -P {{ db_port }} < /home/app/movie-analyst-api/data_model/table_creation_and_inserts.sql
    
    - name: "Deploy and start frontend server"
      shell: node /home/app/movie-analyst-api/server.js > server_log.log ?> server_err.log &
      environment:
        PORT: '{{ port }}'