- hosts: api
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: "Clone frontend repository"
      git:
        repo   : "{{ movie_analyst_api_repo }}"
        update : yes
        dest   : /home/app
    
    - name: "Install MySQL packages"
      apt: pkg={{ item }} state=present
      with_items:
        - mysql-client-core-5.7
        - mysql-client
    
    - name: "Populate DB using mysql-client"
      shell: mysql -u {{ db_user }} -p{{ db_pass }} -h {{ db_host }} -P {{ db_port }} < /home/app/movie-analyst-api/data_model/table_creation_and_inserts.sql
      ignore_errors: yes
      
    - name: get info on frontend container
      docker_container_info:
        name: appBack
      register: result

    - name: Does container exists?
      ansible.builtin.debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Stop container
      docker_container:
        name: appBack
        state: stopped
      when: result.exists

    - name: remove container
      docker_container:
        name: appBack
        state: absent

    - name: remove image
      docker_image:
        state: absent
        name: appBack
        tag: 3
    
    - name: Execute docker container
      docker_container:
        name: appBack
        image: manuel11coral23/my-node-js-backend-image:61
        state: started
        pull: true
        published_ports:
          - "3000:3000"
        env: 
          PORT: '{{ port }}'
          DB_HOST: '{{ db_host }}'
          DB_USER: '{{ db_user }}'
          DB_PASS: '{{ db_pass }}'
          DB_NAME: '{{ db_name }}'
