- hosts: api
  tasks:
    - name: "Clone frontend repository"
      git:
        repo   : "{{ movie_analyst_api_repo }}"
        update : yes
        dest   : /home/app

    - name: "Install npm dependencies"
      npm:
        path: /home/app/movie-analyst-api

    - name: "Install MySQL packages"
      apt: pkg={{ item }} state=present
      with_items:
        - mysql-client-core-5.7
        - mysql-client
    
    - name: "Echoing"
      shell: echo $DB_USER - $DB_PASS - $DB_HOST - $DB_PORT

    - name: "Populate DB using mysql-client"
      shell: mysql -u {{ db_user }} -p{{ db_pass }} -h {{ db_host }} -P {{ db_port }} < /home/app/movie-analyst-api/data_model/table_creation_and_inserts.sql
    
    - name: "Deploy and start frontend server"
      shell: node /home/app/movie-analyst-api/server.js > server_log.log ?> server_err.log &
      environment:
        PORT: '{{ port }}'
        DB_HOST: '{{ db_host }}'
        DB_USER: '{{ db_user }}'
        DB_PASS: '{{ db_pass }}'
        DB_NAME: '{{ db_name }}'
