- hosts: api
  become: yes
  become_user: root
  become_method: sudo

  tasks:
#    - name: "Export env variable"
#      lineinfile: 
#        path: /etc/environment
#        line: export DB_HOST=192.168.56.10
    
#    - name: "Export another env"
#      lineinfile:
#        path: /etc/environment
#        line: export DB_USER=root

#    - name: "Export anotherfd env"
#      lineinfile:
#        path: /etc/environment
#        line: export DB_PASS=F&Bb7_T!$RNkgMKn
    
#    - name: "Export anothefr env"
#      lineinfile:
#        path: /etc/environment
#        line: export DB_NAME=movie_db

    - name: "Clone frontend repository"
      git:
        repo   : "{{ movie_analyst_api_repo }}"
        update : yes
        dest   : /home/app

    - name: "Install npm dependencies"
      npm:
        path: /home/app/movie-analyst-api

    - name: "Install MySQL packages"
      apt: pkg={{ item }} state=present
      with_items:
        - mysql-client-core-5.7
        - mysql-client
    
    - name: "Populate DB using mysql-client"
      shell: mysql -u $DB_USER -p$DB_PASS -h $DB_HOST < /home/app/movie-analyst-api/data_model/table_creation_and_inserts.sql
    
    - name: "Deploy and start frontend server"
      shell: tmux new-session -d -s "back" node /home/app/movie-analyst-api/server.js