- hosts: api
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: get info on frontend container
      docker_container_info:
        name: appBack
      register: result

    - name: Does container exists?
      ansible.builtin.debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Stop container
      docker_container:
        name: appBack
        state: stopped
      when: result.exists

    - name: remove container
      docker_container:
        name: appBack
        state: absent

    - name: remove image
      docker_image:
        state: absent
        name: appBack
        tag: 3
    
    - name: Execute docker container
      docker_container:
        name: 
        image: manuel11coral23/my-node-js-backend-image:61
        state: started
        pull: true
        published_ports:
          - "3030:3030"
        env: 
          PORT: '{{ port }}'
          DB_HOST: '{{ db_host }}'
          DB_USER: '{{ db_user }}'
          DB_PASS: '{{ db_pass }}'
          DB_NAME: '{{ db_name }}'
