- hosts: ui
  tasks:
    - name: "Clone frontend repository"
      git:
        repo   : "{{ movie_analyst_ui_repo }}"
        update : yes
        dest   : /home/app

    - name: "install npm dependencies"
      npm:
        path: /home/app/movie-analyst-ui
    
    - name: "Deploy and start frontend server"
      shell: tmux new-session -d -s "front" node /home/app/movie-analyst-ui/server.js
      environment:
        BACK_HOST: '{{ back_host }}'
