#- import_playbook: all.yml
#- import_playbook: frontend.yml
#- import_playbook: backend.yml
- import_playbook: all-docker.yml
- import_playbook: frontend-docker.yml
- import_playbook: backend-docker.yml