- hosts: tag_Name_back_tf_devops_ramp_up_manuel_corall
  serial: 1
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: get info on frontend container
      docker_container_info:
        name: appBack
      register: result

    - name: Does container exists?
      ansible.builtin.debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Stop container
      docker_container:
        name: appBack
        state: stopped
      when: result.exists

    - name: remove container
      docker_container:
        name: appBack
        state: absent

    - name: remove image
      docker_image:
        state: absent
        name: appBack
    
    - name: Execute docker container
      docker_container:
        name: appBack
        image: manuel11coral23/my-node-js-backend-image:{{ tag }}
        state: started
        pull: true
        published_ports:
          - "3000:3000"
        env: 
          PORT: '{{ port }}'
          DB_HOST: '{{ db_host }}'
          DB_USER: '{{ db_user }}'
          DB_PASS: '{{ db_pass }}'
          DB_NAME: '{{ db_name }}'
      register: my_service_status

    - name: Get container IP
      set_fact:
        container_ip: "{{ my_service_status.ansible_facts.docker_container.NetworkSettings.IPAddress }}"

    - name: Check container
      wait_for:
        host: "{{ container_ip }}"
        port: 3000
