- hosts: ui
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: get info on frontend container
      docker_container_info:
        name: appFront
      register: result

    - name: Does container exists?
      ansible.builtin.debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Stop container
      docker_container:
        name: appFront
        state: stopped
      when: result.exists

    - name: remove container
      docker_container:
        name: appFront
        state: absent

    - name: remove image
      docker_image:
        state: absent
        name: appFront
        tag: 3
    
    - name: Execute docker container
      docker_container:
        name: appFront
        image: manuel11coral23/my-node-js-frontend-image:3
        state: started
        pull: true
        published_ports:
          - "3030:3030"
        env: 
          BACK_HOST: '{{ back_host }}'
